<a href="https://colab.research.google.com/github/DhanadurgaLakshmi/AI-Engineering/blob/main/Day_17_initialization_normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

x = tf.constant([
    [2.0, 4.0, 6.0],
    [8.0, 10.0, 12.0]
])

# Batch Normalization
batch_norm = tf.keras.layers.BatchNormalization()
bn_output = batch_norm(x, training=True)

print("Original:")
print(x.numpy())

print("\nBatchNorm:")
print(bn_output.numpy())

# Layer Normalization
layer_norm = tf.keras.layers.LayerNormalization()
ln_output = layer_norm(x)

print("\nLayerNorm:")
print(ln_output.numpy())

# Learnable parameters
print("\nBatchNorm weights:")
for weight in batch_norm.weights:
    print(weight.name, weight.shape)

print("\nLayerNorm weights:")
for weight in layer_norm.weights:
    print(weight.name, weight.shape)

Original:
[[ 2.  4.  6.]
 [ 8. 10. 12.]]

BatchNorm:
[[-0.9999444  -0.9999443  -0.99994445]
 [ 0.99994445  0.99994445  0.99994445]]

LayerNorm:
[[-1.2245153  0.         1.2245152]
 [-1.2245154  0.         1.224515 ]]

BatchNorm weights:
gamma (3,)
beta (3,)
moving_mean (3,)
moving_variance (3,)

LayerNorm weights:
gamma (3,)
beta (3,)
